name: network_service
description: Service that manages network requests with Dio
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  very_good_analysis: ^3.1.0
