name: path_provider_service
description: Service that retrieves paths to app directories
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  very_good_analysis: ^3.1.0
